import type { Metadata } from "next";
import "./globals.css";
import Nav from "./[components]/Nav";
import AuthProvider from "./[components]/AuthProvider";

export const metadata: Metadata = {
  title: "Next Js Authentication",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className="bg-gray-100">
          <Nav />
          <div className="m-2">{children}</div>
        </body>
      </AuthProvider>
    </html>
  );
}
